# Random seed
SEED: 101

# experiment name
exp_name: "supervised_MLC_aug_2_fix/"

# path to json file with annotations
json_file_path_train: "/misc/lmbraid19/argusm/CLUSTER/multimed/NSEG2015_2/train.json"
json_file_path_test: "/misc/lmbraid19/argusm/CLUSTER/multimed/NSEG2015_2/test.json"

# path to the images' folder
images_path: "/misc/lmbraid19/argusm/CLUSTER/multimed/NSEG2015_2/JPEGImages/"

# path to output
output_path: "/misc/student/alzouabk/Thesis/supervised_multi_label_classification/outputs/"

# data loading parameters:
shuffle_dataset: True
batch_size: 18

# augmentation settings:
elasticdeform_control_points_num: 3
elasticdeform_sigma: 20
elasticdeform_p: 0.5

RandomResizedCrop_size: 512
RandomResizedCrop_scale: [0.7, 0.9]
RandomResizedCrop_p: 0

RandomRotation_range: 45
RandomRotation_p: 1

RandomAffine_rotate: 0
RandomAffine_translate: [0.2, 0.2]
RandomAffine_scale: [0.5, 1.25]
RandomAffine_shear: 0.2
RandomAffine_p: 0

adjust_brightness_factor: 0.01
adjust_brightness_p: 0

GaussianBlur_kernel_size: [5, 5]
GaussianBlur_sigma: [.1, 2.]
GaussianBlur_p: 0

RandomErasing_scale: [0.01, 0.1]
RandomErasing_ratio: [0.5, 2.0]
RandomErasing_p: 0

RandomHorizontalFlip_p: 0.5

Normalize_mean: [0.184]
Normalize_std: [0.055]
Normalize_p: 1 # need to be 0 or 1

# model parameters:
pretrained: True
requires_grad: True

# learning parameters
lr: 0.0005
epochs: 40

# Evaluate?
evaluate: True

# Visualize?
plot_curves: True

# multi channel?
num_channels: 1