# Random seed
SEED: 101

# experiment name
exp_name: "default_run/"

# path to json file with annotations
json_file_path_train: "/misc/lmbraid19/argusm/CLUSTER/multimed/NSEG2015_2/train.json"
json_file_path_test: "/misc/lmbraid19/argusm/CLUSTER/multimed/NSEG2015_2/test.json"

# path to the images' folder
images_path: "/misc/lmbraid19/argusm/CLUSTER/multimed/NSEG2015_2/JPEGImages/"

# path to output
output_path: "/misc/student/alzouabk/Thesis/supervised_multi_label_classification/outputs/"

# data loading parameters:
shuffle_dataset: True
batch_size: 18

# multi channel?
num_channels: 3

# model parameters:
pretrained: True
requires_grad: True

# learning parameters
lr: 0.0005
epochs: 40

# Evaluate?
evaluate: True

# Visualize?
plot_curves: True